# Generated by Django 5.2.8 on 2025-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
