# Generated by Django 5.2.8 on 2025-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_events_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
