# Generated by Django 5.2.8 on 2025-12-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clubs_title_services_title_support_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='other',
            field=models.TextField(default='', help_text='Напишите адресс, время, ссылку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='order',
            field=models.IntegerField(help_text='Укажите номер изображения(0 - Главное изображение)'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(help_text='Перед добавлением новой недели удалите предыдущую', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(help_text='Пропорция картинки 1.6:1', upload_to='news/main/'),
        ),
    ]
