# Generated by Django 5.2.8 on 2025-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clubs_other_alter_events_order_alter_events_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(null=True, upload_to='services/images/'),
        ),
    ]
