# Generated by Django 5.2.8 on 2025-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_services_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/'),
        ),
    ]
