# Generated by Django 5.2.8 on 2025-12-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_services_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayvka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('vk_link', models.CharField(verbose_name='Ссылка на социальную сеть ВКонтакте')),
                ('workplace', models.CharField(max_length=300, verbose_name='Место работы/учёбы')),
                ('initiative_name', models.CharField(max_length=200, verbose_name='Название инициативы')),
                ('initiative_goal', models.TextField(verbose_name='Цель инициативного предложения')),
                ('initiative_description', models.TextField(verbose_name='Описание инициативного предложения')),
                ('initiative_format', models.CharField(choices=[('stock', 'Акция'), ('discussion', 'Дискуссия'), ('class', 'Занятие'), ('games', 'Игры'), ('competition', 'Конкурс'), ('conference', 'Конференция'), ('holiday', 'Праздник'), ('performance', 'Представление'), ('thematic_meeting', 'Тематическая встреча'), ('broadcast', 'Трансляция'), ('ceremony', 'Церемония'), ('information_support', 'Информационное сопровождение'), ('support', 'Кадровая поддержка'), ('other', 'Другое')], max_length=50, verbose_name='Формат инициативы')),
                ('other_format_details', models.TextField(verbose_name="Если выбрали 'Другое', распишите формат")),
                ('initiative_date', models.DateField(verbose_name='Дата проведения инициативы')),
                ('initiative_time', models.CharField(verbose_name='Время проведения инициативы')),
                ('expected_participants', models.CharField(choices=[('10-30', '10-30 человек'), ('30-50', '30-50 человек'), ('50-100', '50-100 человек'), ('100+', 'Более 100 человек')], max_length=10, verbose_name='Предполагаемое количество участников')),
                ('room_type', models.CharField(choices=[('conference_room', 'Конференц-зал'), ('digital_workshop', 'Цифровая мастерская'), ('photo_studio', 'Фотостудия'), ('food_court', 'Фудкорт'), ('soldering_workshop', 'Паяльная мастерская'), ('cyberclass', 'Киберкласс'), ('lobby_cyber_class', 'Холл у киберкласса'), ('coworking', 'Коворкинг')], max_length=50, verbose_name='Тип помещения')),
                ('technical_equipment', models.TextField(verbose_name='Техническое оснащение инициативы')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('personal_data_agreement', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('status', models.CharField(choices=[('review', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонена')], default='review', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='clubs',
            name='other',
            field=models.TextField(help_text='Напишите адресс, время, ссылку. Ссылка должна быть полной.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(help_text='Ссылка должна быть полной.'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(help_text='Ссылка должна быть полной.'),
        ),
    ]
