# Generated by Django 5.2.8 on 2025-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_zayvka_alter_clubs_other_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayvka',
            name='other_format_details',
            field=models.TextField(blank=True, verbose_name="Если выбрали 'Другое', распишите формат"),
        ),
    ]
