# Generated by Django 5.2.8 on 2025-12-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_zayvka_other_format_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayvka',
            name='comments',
            field=models.TextField(verbose_name='Комментарии'),
        ),
    ]
