# Generated by Django 5.2.8 on 2026-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_zayvka_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayvka',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='zayvka',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принято', 'Принято'), ('Отклонена', 'Отклонена')], default='На рассмотрении', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
