# Generated by Django 5.2.8 on 2026-03-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_zayvka_comments_alter_zayvka_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='product',
            new_name='news',
        ),
    ]
